### ISSUE TITLE
Isso language to English

### ISSUE THREAD

**Issue by frenchvandal** [angristan/Casper-XYZ#12]
Just a little suggestion: I see that your Ghost blog is in English but the Isso section shows up in French.

If you want to match Isso language to Ghost’s, you can add this data attribute to your Isso client configuration:

`data-isso-lang="{{@site.lang}}"`

**Comment by angristan** [comment]
My devices are in English so Isso shows up in English for me. I might as well make it consistent, thanks for telling me.
