### ISSUE TITLE
Install Renovate

### ISSUE THREAD

**Issue by frenchvandal** [angristan/Casper-XYZ#14]
You can automatically update the dependencies in package.json and yarn.lock with Renovate.

You need to install the GitHub App [Renovate](https://github.com/apps/renovate) and configure with renovate.json 

I have used that one:
`{
  "enabled": true,
  "automerge": true,
  "rebaseWhen": "conflicted",
  "node": {
    "supportPolicy": ["lts_latest"]
  }
}`

**Comment by angristan** [comment]
https://github.com/TryGhost/Casper already uses it. (I'm merging upstream every so often)
