### ISSUE TITLE
Add i18n

### ISSUE THREAD

**Issue by gllmhyt** [angristan/Casper-XYZ#3]
Since a few versions, [Ghost themes supports internationalisation](https://blog.ghost.org/theme-translations/). Sadly, Casper hasn't been updated by the core team. Nevertheless, there is [WorldCasper2](https://github.com/juan-g/WorldCasper2), aka Casper made translatable into any language. It might be a good idea to rebase your fork on it and therefore support internationalisation.

**Comment by frenchvandal** [comment]
It seems that Casper i18n is not maintained anymore.

**Comment by gllmhyt** [comment]
@frenchvandal WorldCasper2 was a fork of Casper v2 made to add internationalisation support. One should be made for Caper v3.
